{% set python_min = "3.11" %}
{% set name = "napari-wsi" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_wsi-{{ version }}.tar.gz
  sha256: 0839da85aa6f71e907ec2029065cc6e49d965b5b0f3e102c704afed7f67b0385

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - dask >=2025.1
    - magicgui >=0.10
    - numpy >=1.26
    - openslide >=4.0
    - openslide-python >=1.4
    - pillow >=11.1
    - python >={{ python_min }}
    - rasterio >=1.4
    - universal_pathlib >=0.2
    - wsidicom >=0.22
    - zarr >=3.0

test:
  imports:
    - napari_wsi
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AstraZeneca/napari-wsi
  summary: A plugin to read whole slide images within napari.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pmplewa
