{% set name = "napari-wsi" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_wsi-{{ version }}.tar.gz
  sha256: 8e7bbf5c1e8d64ecebfe079bb8e29d31710c07c87b038a7654ef157138ecaf7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8,<3.11
  run:
    - dask-core >=2022
    - imagecodecs >=2022
    - magicgui <1.0.0
    - matplotlib-base >=3.0.0,<4.0.0
    - napari >=0.4.0,<0.5.0
    - numpy >=1.0.0,<2.0.0
    - pydantic !=1.10.0
    - python >=3.8,<3.11
    - rasterio >=1.0.0,<2.0.0
    - tifffile >=2022
    - zarr >=2.0.0,<3.0.0

test:
  imports:
    - napari_wsi
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AstraZeneca/napari-wsi
  summary: A plugin to read whole slide images within napari.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - pmplewa
